- hosts: all
  become: true
  environment:
    KUBECONFIG: /home/azureuser/.kube/config

  tasks:
    - name: Delete old deployment
      shell: kubectl delete -f /home/azureuser/deployment.yml

    - name: Delete old service
      shell: kubectl delete -f /home/azureuser/service.yml

    - name: Create new deployment
      shell: kubectl apply -f /home/azureuser/deployment.yml

    - name: Create new service
      shell: kubectl apply -f /home/azureuser/service.yml
