kind: Deployment
apiVersion: apps/v1
metadata:
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: anishashende/demo-pipeline:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000 # If your app runs on 5000 inside the container (like FastAPI, Flask etc.)
