apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31200
