kind: Service
apiVersion: v1
metadata:
  name: chatbot-service
  labels:
    app: chatbot
spec:
  ports:
    - port: 80 # Port exposed OUTSIDE
      targetPort: 5000 # Port inside the container
      nodePort: 31200 # Node port (for external access)
  selector:
    app: chatbot
  type: LoadBalancer
